name: 'steam-price-action'
description: 'Fetches prices for steam products from key reseller (G2A.com)'
author: 'Stefan Breitenstein'
branding:
  icon: activity
  color: purple
inputs:
  input:
    description: 'given json like described in the schema.json'
    required: true
outputs:
  tsv:
    description: 'Report as tsv'

runs:
  using: 'node16'
  main: 'dist/index.js'
